# Site settings
title: SteelHacks 2021
description: > # this means to ignore newlines until "baseurl:"
  University of Pittsburgh's hackathon! Feb 19th-21th, 20201.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://steelhacks.com" # the base hostname & protocol for your site
registration_url: "https://forms.gle/FsnhYFTUgJP4vAJj6"
# Build settings
markdown: kramdown

facebook_username: steelhacks
twitter_username: PittSteelHacks
#instagram_username: steelhacks
