# Site settings
title: SteelHacks 2018
description: > # this means to ignore newlines until "baseurl:"
  University of Pittsburgh's hackathon! February 24-25th, 2018.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://steelhacks.com" # the base hostname & protocol for your site
twitter_username: steelhacks
registration_url: "https://steelhacks2018.typeform.com/to/CmTuws"
# Build settings
markdown: kramdown
