# Site settings
title: SteelHacks 2019
description: > # this means to ignore newlines until "baseurl:"
  University of Pittsburgh's hackathon! March 1st-2nd, 2019.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://steelhacks.com" # the base hostname & protocol for your site
twitter_username: steelhacks
registration_url: "https://my.mlh.io/oauth/authorize?client_id=9fd4a6f079e432755692b825df2768f185fba38047df255ed385add0fc89a12e&redirect_uri=http%3A%2F%2Fsteelhacks.com%2Fregistered&response_type=token"
# Build settings
markdown: kramdown
